# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "hotfix/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main
      - "feature/**"
      - "hotfix/**"
      - "bugfix/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: poetry run pytest
